"""Writer agent: turns approved analysis into a cited Markdown memo.

Production seam: a real deployment would send the approved analysis and
findings to an LLM and ask it to draft client-ready prose. The offline demo
instead uses a deterministic Markdown template (``_render_memo``); the part
that is *not* a shortcut, and that would remain in a production
implementation exactly as written here, is that every claim placed into the
memo is routed through the ``citation_checker`` tool before being trusted,
via this agent's explicit tool allow-list.

Required memo sections are exposed as ``REQUIRED_MEMO_SECTIONS`` so the
evaluation harness can check memo completeness against the same list this
agent uses to build the memo, rather than duplicating a second copy of the
section names.
"""

from __future__ import annotations

from typing import Any, Mapping

from orchestrator.agent_base import Agent, AgentOutput

WRITER_SYSTEM_PROMPT = (
    "You are a professional writer at an advisory firm producing a "
    "client-ready research and analysis memo. Every factual claim must "
    "carry an inline citation back to the exact source chunk it came from, "
    "and every citation must pass the citation-checker tool before it is "
    "included. Write in clear, concise, professional prose."
)

REQUIRED_MEMO_SECTIONS: tuple[str, ...] = (
    "Executive Summary",
    "Key Findings",
    "Thematic Analysis",
    "Risks",
    "Opportunities",
    "Recommendation",
    "Sources",
)


def _cited_bullet(text: str, chunk_id: str, is_valid: bool) -> str:
    marker = f"[{chunk_id}]" if is_valid else f"[{chunk_id} - UNVERIFIED]"
    return f"- {text} {marker}"


def _render_memo(
    findings: list[Mapping[str, Any]],
    analysis: Mapping[str, Any],
    citation_results: dict[str, Mapping[str, Any]],
) -> str:
    """Renders the final Markdown memo from findings, analysis, and citation results.

    Args:
        findings: Findings produced by the researcher agent.
        analysis: Approved analysis content produced by the analyst agent.
        citation_results: Mapping of ``finding_id`` -> citation-check result
            dict (as returned by the ``citation_checker`` tool).

    Returns:
        The full memo as a Markdown string containing every section in
        ``REQUIRED_MEMO_SECTIONS``.
    """
    recommendation = analysis["recommendation"]
    themes: Mapping[str, list[Mapping[str, Any]]] = analysis["themes"]
    risks: list[Mapping[str, Any]] = analysis["risks"]
    opportunities: list[Mapping[str, Any]] = analysis["opportunities"]

    lines: list[str] = []
    lines.append("# Research & Analysis Memo")
    lines.append("")
    lines.append(
        "*Generated by an offline, deterministic demo pipeline. See "
        "the project README for how a production LLM would be plugged in.*"
    )
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(
        f"Recommendation: **{recommendation['label']}** "
        f"(net signal score {recommendation['score']:+.2f} on a -100..+100 scale). "
        f"{recommendation['rationale']}"
    )
    lines.append("")

    lines.append("## Key Findings")
    lines.append("")
    for finding in findings:
        result = citation_results.get(finding["finding_id"], {})
        lines.append(
            _cited_bullet(
                finding["text"], finding["chunk_id"], bool(result.get("is_valid"))
            )
        )
    lines.append("")

    lines.append("## Thematic Analysis")
    lines.append("")
    for theme_name, theme_findings in themes.items():
        lines.append(f"### {theme_name}")
        for finding in theme_findings:
            result = citation_results.get(finding["finding_id"], {})
            lines.append(
                _cited_bullet(
                    finding["text"], finding["chunk_id"], bool(result.get("is_valid"))
                )
            )
        lines.append("")

    lines.append("## Risks")
    lines.append("")
    if risks:
        for finding in risks:
            result = citation_results.get(finding["finding_id"], {})
            lines.append(
                _cited_bullet(
                    finding["text"], finding["chunk_id"], bool(result.get("is_valid"))
                )
            )
    else:
        lines.append("- No material risk signals identified in the source documents.")
    lines.append("")

    lines.append("## Opportunities")
    lines.append("")
    if opportunities:
        for finding in opportunities:
            result = citation_results.get(finding["finding_id"], {})
            lines.append(
                _cited_bullet(
                    finding["text"], finding["chunk_id"], bool(result.get("is_valid"))
                )
            )
    else:
        lines.append("- No material opportunity signals identified in the source documents.")
    lines.append("")

    lines.append("## Recommendation")
    lines.append("")
    lines.append(
        f"**{recommendation['label']}** -- {recommendation['opportunity_count']} "
        f"opportunity signal(s) versus {recommendation['risk_count']} risk signal(s). "
        f"{recommendation['rationale']}"
    )
    lines.append("")

    lines.append("## Sources")
    lines.append("")
    source_ids = sorted({finding["source_id"] for finding in findings})
    for source_id in source_ids:
        lines.append(f"- `{source_id}`")
    lines.append("")

    return "\n".join(lines)


class WriterAgent(Agent):
    """Renders approved analysis and findings into a final cited Markdown memo."""

    def __init__(self, tool_registry, llm_client=None) -> None:  # type: ignore[no-untyped-def]
        super().__init__(
            name="writer_agent",
            system_prompt=WRITER_SYSTEM_PROMPT,
            allowed_tools=["citation_checker"],
            tool_registry=tool_registry,
            llm_client=llm_client,
        )

    def act(self, input_context: Mapping[str, Any]) -> AgentOutput:
        """Writes the final memo, validating every claim's citation first.

        Args:
            input_context: Must contain ``approved`` (bool), ``analysis``
                (the analyst's content dict), ``findings`` (the researcher's
                findings list), and ``chunks`` (the full parsed source
                corpus, needed by the citation checker).

        Returns:
            An ``AgentOutput`` whose ``content`` has keys ``memo_markdown``
            (``str | None``), ``status`` (``"complete"`` or
            ``"blocked_pending_revision"``), and ``citation_results``.
        """
        if not input_context.get("approved", False):
            return AgentOutput(
                agent_name=self.name,
                content={
                    "memo_markdown": None,
                    "status": "blocked_pending_revision",
                    "citation_results": {},
                },
                metadata={"used_llm": self.uses_real_llm()},
            )

        analysis = input_context["analysis"]
        findings = list(input_context["findings"])
        chunks = list(input_context["chunks"])

        if self.uses_real_llm():
            prompt = "\n".join(f"- {f['text']} [{f['chunk_id']}]" for f in findings)
            _ = self.llm_client(self.system_prompt, prompt)  # pragma: no cover
            raise NotImplementedError(
                "Real LLM memo drafting is a documented extension point, not "
                "part of the offline demo path. Construct WriterAgent without "
                "an llm_client to use the deterministic template."
            )

        citation_results: dict[str, Mapping[str, Any]] = {}
        for finding in findings:
            result = self.call_tool(
                "citation_checker",
                claim_text=finding["text"],
                chunk_id=finding["chunk_id"],
                source_chunks=chunks,
            )
            citation_results[finding["finding_id"]] = result

        memo_markdown = _render_memo(findings, analysis, citation_results)
        self.remember(memo_markdown)

        valid_count = sum(1 for r in citation_results.values() if r.get("is_valid"))
        total_count = len(citation_results)

        return AgentOutput(
            agent_name=self.name,
            content={
                "memo_markdown": memo_markdown,
                "status": "complete",
                "citation_results": citation_results,
            },
            metadata={
                "citation_validity_rate": (valid_count / total_count) if total_count else 1.0,
                "num_citations_checked": total_count,
                "used_llm": self.uses_real_llm(),
            },
        )
